### ISSUE TITLE
Need Meetup Link

### ISSUE THREAD

**Issue by rebelweb** [effinghamdevelopergroup/effinghamdevelopergroup.github.io#1]
We need the link to the meetup page. We will need to link the social icon to that page.

**Comment by MeyerJoey** [comment]
Ran into a subscription plan. Looks like 60-80 a year. I'll need to wait until Tuesday on this decision.
![image](https://cloud.githubusercontent.com/assets/7315193/25789938/970115c0-337a-11e7-8dc2-a38a771c6cc2.png)

**Comment by rebelweb** [comment]
Plan is bought just need to implement now
